env: "local"
database:
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "postgres"
  dbname: "url_sentinel"
  sslmode: "disable"
http_server:
  address: "localhost:8080"
  read_timeout: 5s
  write_timeout: 10s
  idle_timeout: 60s
  shutdown_timeout: 10s